-- start of appending to responces annoyence -----------------------------------------------------------------------------------------------------------------
pal:SetNewAnnoyanceRespoces( 1, "Now stop repeating your self." )
pal:SetNewAnnoyanceRespoces( 1, "Now cut the reapeat." )
pal:SetNewAnnoyanceRespoces( 1, "Why again." )
pal:SetNewAnnoyanceRespoces( 1, "Just so you know I already told you this by the way." )
pal:SetNewAnnoyanceRespoces( 1, "You say this again as well." )
pal:SetNewAnnoyanceRespoces( 1, "Now stop reapeating yourself." )
pal:SetNewAnnoyanceRespoces( 1, "Can you now stop asking that." )

-- end of appending to responces annoyence start of annoyed responces ----------------------------------------------------------------------------------------
pal:SetNewAnnoyanceRespoces( 2, "I wont tell you again." )
pal:SetNewAnnoyanceRespoces( 2, "I dont think I should tell you again." )
pal:SetNewAnnoyanceRespoces( 2, "I will not tell you again." )
pal:SetNewAnnoyanceRespoces( 2, "I told you this enougth times already." )
pal:SetNewAnnoyanceRespoces( 2, "Please shut up and stop asking the same question over and over again." )
pal:SetNewAnnoyanceRespoces( 2, "Shut up and stop asking the same question over and over again." )
pal:SetNewAnnoyanceRespoces( 2, "Please stop asking the same question over and over again." )
pal:SetNewAnnoyanceRespoces( 2, "Please stop asking the same question." )
pal:SetNewAnnoyanceRespoces( 2, "Please shut up and stop asking the same question" )
pal:SetNewAnnoyanceRespoces( 2, "I am not going to tell you again." )
pal:SetNewAnnoyanceRespoces( 2, "If you cant think of anything else to ask then you should leave." )
pal:SetNewAnnoyanceRespoces( 2, "If you cant think of anything else to ask then you should need leave." )
pal:SetNewAnnoyanceRespoces( 2, "If you cant think of anything else to ask then you could leave." )
pal:SetNewAnnoyanceRespoces( 2, "If you cant think of anything else to ask then leave." )
pal:SetNewAnnoyanceRespoces( 2, "If you cant come up with anything else to ask then you should leave." )
pal:SetNewAnnoyanceRespoces( 2, "If you cant come up with of anything else to ask then you should need leave." )
pal:SetNewAnnoyanceRespoces( 2, "If you cant come up with of anything else to ask then you could leave." )
pal:SetNewAnnoyanceRespoces( 2, "If you cant come up with of anything else to ask then leave." )
