pal:AddNewSynonymsGroup( 'syngroup_21', {'weight','mass','poundage'} )
pal:AddNewSynonymsGroup( 'syngroup_56', {'fast','agile','brisk','quick','rapid','swift'} )
pal:AddNewSynonymsGroup( 'syngroup_74', {'belly','gut','abdomen'} )
pal:AddNewSynonymsGroup( 'syngroup_84', {'cup','glass'} )
pal:AddNewSynonymsGroup( 'syngroup_111', {'make','create','build','assemble'} )
pal:AddNewSynonymsGroup( 'syngroup_131', {'money','cash','currency'} )
pal:AddNewSynonymsGroup( 'syngroup_151', {'mean','greedy','salfish'} )
pal:AddNewSynonymsGroup( 'syngroup_173', {'delete','remove','destroy'} )
pal:AddNewSynonymsGroup( 'syngroup_208', {'bugs','insects','critters','the cralwles'} )
pal:AddNewSynonymsGroup( 'syngroup_233', {'bad','horrible','meansalfish'} )
pal:AddNewSynonymsGroup( 'syngroup_258', {'love','romance','','butterflys'} )
pal:AddNewSynonymsGroup( 'syngroup_283', {'online','active','powered up'} )
pal:AddNewSynonymsGroup( 'syngroup_298', {'solve','complete'} )
pal:AddNewSynonymsGroup( 'syngroup_317', {'liter','junk','garbage'} )
pal:AddNewSynonymsGroup( 'syngroup_338', {'house','home','settlment'} )
pal:AddNewSynonymsGroup( 'syngroup_351', {'gain','collect'} )
pal:AddNewSynonymsGroup( 'syngroup_369', {'take','snatch','steal'} )
pal:AddNewSynonymsGroup( 'syngroup_386', {'business','company'} )
pal:AddNewSynonymsGroup( 'syngroup_418', {'meaning','definition','the point of'} )
pal:AddNewSynonymsGroup( 'syngroup_443', {'anime','japanese animation'} )
pal:AddNewSynonymsGroup( 'syngroup_474', {'scrambled','broken','mixed','damaged'} )
pal:AddNewSynonymsGroup( 'syngroup_505', {'hard','solid','unmoveing','difficult'} )
pal:AddNewSynonymsGroup( 'syngroup_529', {'backup','copy','redunt copy'} )
pal:AddNewSynonymsGroup( 'syngroup_551', {'happy','smileing','gowing'} )
pal:AddNewSynonymsGroup( 'syngroup_569', {'fleas','bugs','incets'} )
pal:AddNewSynonymsGroup( 'syngroup_589', {'child','kid','youngling'} )
pal:AddNewSynonymsGroup( 'syngroup_605', {'resume','continue'} )
pal:AddNewSynonymsGroup( 'syngroup_633', {'friends','pals','buddyies','mates'} )
pal:AddNewSynonymsGroup( 'syngroup_643', {'girl','lady'} )
pal:AddNewSynonymsGroup( 'syngroup_667', {'powerball','ball of power'} )
pal:AddNewSynonymsGroup( 'syngroup_684', {'expect','forshadow'} )
pal:AddNewSynonymsGroup( 'syngroup_707', {'expecting','forshadowing'} )
pal:AddNewSynonymsGroup( 'syngroup_736', {'music','soundtrack','beets','tunes'} )
pal:AddNewSynonymsGroup( 'syngroup_748', {'movie','video'} )
pal:AddNewSynonymsGroup( 'syngroup_769', {'car','vehical','motorcar'} )
pal:AddNewSynonymsGroup( 'syngroup_781', {'earth','world'} )
pal:AddNewSynonymsGroup( 'syngroup_796', {'big','huge','large'} )
pal:AddNewSynonymsGroup( 'syngroup_811', {'airplane','plane'} )
pal:AddNewSynonymsGroup( 'syngroup_831', {'tell','talk to','inform'} )
pal:AddNewSynonymsGroup( 'syngroup_846', {'private','hidden'} )
pal:AddNewSynonymsGroup( 'syngroup_866', {'convert','switch','flip'} )
pal:AddNewSynonymsGroup( 'syngroup_879', {'stone','cobblr'} )
pal:AddNewSynonymsGroup( 'syngroup_893', {'disease','death'} )
pal:AddNewSynonymsGroup( 'syngroup_909', {'good','glad','great'} )
pal:AddNewSynonymsGroup( 'syngroup_924', {'teeth','chompers'} )
pal:AddNewSynonymsGroup( 'syngroup_957', {'cold','frozen','chilled','frozen solid'} )
pal:AddNewSynonymsGroup( 'syngroup_964', {'babies'} )
pal:AddNewSynonymsGroup( 'syngroup_982', {'trans','transgender'} )
pal:AddNewSynonymsGroup( 'syngroup_995', {'cute','butiful'} )
pal:AddNewSynonymsGroup( 'syngroup_1008', {'deserve','need'} )
