pal:SetNewIDKresponces( "I dont understand what you said" )
pal:SetNewIDKresponces( "I dont understand what you said user" )
pal:SetNewIDKresponces( "I can not process what you are talking about" )
pal:SetNewIDKresponces( "I can not process what you are talking about user" )
pal:SetNewIDKresponces( "what you said can not be understood" )
pal:SetNewIDKresponces( "what you said can not be understood user" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )
pal:SetNewIDKresponces( "" )

