pal:SetNewIDKresponces( "I dont understand what you said" )
pal:SetNewIDKresponces( "I dont understand what you said user" )
pal:SetNewIDKresponces( "I can not process what you are talking about" )
pal:SetNewIDKresponces( "I can not process what you are talking about user" )
pal:SetNewIDKresponces( "what you said can not be understood" )
pal:SetNewIDKresponces( "what you said can not be understood user" )
pal:SetNewIDKresponces( "I do not understand" )
pal:SetNewIDKresponces( "I do not understand user" )
pal:SetNewIDKresponces( "I can not understand you" )
pal:SetNewIDKresponces( "I can not understand you user" )
pal:SetNewIDKresponces( "I can not understand what you saying" )
pal:SetNewIDKresponces( "I can not understand what you saying user" )
pal:SetNewIDKresponces( "please speak a little bit more clearly" )
pal:SetNewIDKresponces( "please speak a little bit more clearly user" )
pal:SetNewIDKresponces( "can you try rephrasing your english" )
pal:SetNewIDKresponces( "can you try rephrasing your english user" )
pal:SetNewIDKresponces( "please speak better" )
pal:SetNewIDKresponces( "please speak better user" )
pal:SetNewIDKresponces( "can you just check for spelling mistakes and then say it again" )
pal:SetNewIDKresponces( "can you just check for spelling mistakes and then say it again user" )
pal:SetNewIDKresponces( "please check your spelling" )
pal:SetNewIDKresponces( "please check your spelling user" )

